CREATE TABLE role_mst (
    role_id INT PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(50) NOT NULL
);

CREATE TABLE department_mst (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL
);

CREATE TABLE user_mst (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    department_id INT NOT NULL,
    role_id INT NOT NULL,
    first_login_flag BOOLEAN NOT NULL,
    password VARCHAR(255) NOT NULL,
    employee_number VARCHAR(20) NOT NULL UNIQUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);