spring.application.name=demo

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/portfolio_db}

spring.datasource.username=${DB_USERNAME}

spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=${PORT:8080}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}